source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BSForegroundNotification_Example', :exclusive => true do
  pod "BSForegroundNotification", :path => "../"
end

target 'BSForegroundNotification_Tests', :exclusive => true do
  pod "BSForegroundNotification", :path => "../"

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
